---
# handlers file for ansible-role-docker
- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: true
  tags:
    - docker

- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
  tags:
    - docker
